### ISSUE TITLE
ProgressEvent { isTrusted: [Getter] } when trying to generate image

### ISSUE THREAD

**Issue by Soulthrower** [digidem/mapbox-map-image-export#2]
Hey ! 

Since today, i get this message every time i try to generate an image ! 

`ProgressEvent { isTrusted: [Getter] }`

I've already seen it once before when i tried to generate two images at the same time using the same access token but it never shown again afterwards, since i've stopped trying to generate multiple images at the same time.

Now it shows like 3 to 4 times every time i try to generate a single image.
I've checked my mapbox account and i'm at 130 requests out of 50k so it cannot be linked to the request number limitation. Since nothing changed on the project I don't understand the reason why it stopped working ! 

Any help on this would be greatly appreciated ! :) 
Thanks ! 😄

**Comment by gmaclennan** [comment]
Hi can you share the command that you are trying to run and the full error message?

**Comment by Soulthrower** [comment]
Hey,

Thank you for your quick reply !

Finally found the answer to my question :) 
It's working again finally ! The problem was that my style file was badly formatted ! I've rearranged it and now it works like a charm. 

Hope this helps anyone !
