### ISSUE TITLE
Is it my human error or is it broken?

### ISSUE THREAD

**Issue by daanvr** [digidem/mapbox-map-image-export#4]
Thees are the two comand I write in my macOS Terminal:
`export MAPBOX_TOKEN=pk.eyJ1IjoiZGFhbnZyIiwiYSI6ImNpdTJmczN3djAwMHEyeXBpNGVndWtuYXEifQ.GYZf7r9gTfQL3W-GpmmJ3A`
and
`export-map mapbox://styles/daanvr/ciw1eozkr00dd2jscswkbdfvg -b=6.8056,52.2232,6.8917,52.2648 -t=$MAPBOX_TOKEN -o=/Users/daan/Downloads/mapimgtest.png -w=11in -h=11in`

The response is:

> [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
> [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
> [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
> [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
> [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
> 1056 0.2794
> SCALE: 1:20977.45022865984
> ZOOM: 13.0740901678402
> Error: http status 200 returned without content.
> Error: http status 200 returned without content.
> Error: http status 200 returned without content.
> Error: http status 200 returned without content.
> Error: http status 200 returned without content.
> TypeError: emitter.prependListener is not a function
>     at prependListener (_stream_readable.js:19:20)
>     at BufferPeekStream.Readable.pipe (_stream_readable.js:584:3)
>     at pipe (/usr/local/lib/node_modules/mapbox-map-image-export/node_modules/pump/index.js:54:15)
>     at Array.reduce (native)
>     at pump (/usr/local/lib/node_modules/mapbox-map-image-export/node_modules/pump/index.js:77:18)
>     at Pumpify.setPipeline (/usr/local/lib/node_modules/mapbox-map-image-export/node_modules/pumpify/index.js:39:5)
>     at PixelMultiStream.onFormat (/usr/local/lib/node_modules/mapbox-map-image-export/node_modules/mosaic-image-stream/lib/stitch-image-stream.js:47:19)
>     at PixelMultiStream.EventEmitter.emit (/usr/local/lib/node_modules/mapbox-map-image-export/node_modules/events/events.js:81:17)
>     at PixelMultiStream.onFormat (/usr/local/lib/node_modules/mapbox-map-image-export/node_modules/mosaic-image-stream/lib/pixel-multi-stream.js:49:10)
>     at Pumpify.EventEmitter.emit (/usr/local/lib/node_modules/mapbox-map-image-export/node_modules/events/events.js:81:17)

**Comment by gmaclennan** [comment]
Please try the latest version v2.2.0 and report back if it works.
