### ISSUE TITLE
TypeError: emitter.prependListener is not a function

### ISSUE THREAD

**Issue by kaluta** [digidem/mapbox-map-image-export#5]
I'm getting this error:

> export-map mapbox://styles/mapbox/streets-v9 -b=-7.1354,57.9095,-6.1357,58.516 -t=$MAPBOX_TOKEN

>[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
>[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
>[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
>[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
>[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

>1056 0.2794
>SCALE: 1:311383.2778040875
>ZOOM: 8.960893006284609

>TypeError: emitter.prependListener is not a function
>    at prependListener (_stream_readable.js:19:20)
>    at BufferPeekStream.Readable.pipe (_stream_readable.js:584:3)
>    at pipe (/usr/local/lib/node_modules/mapbox-map-image->export/node_modules/pump/index.js:54:15)
>    at Array.reduce (native)
>    at pump (/usr/local/lib/node_modules/mapbox-map-image->export/node_modules/pump/index.js:77:18)
>    at Pumpify.setPipeline (/usr/local/lib/node_modules/mapbox-map-image->export/node_modules/pumpify/index.js:39:5)
>    at PixelMultiStream.onFormat (/usr/local/lib/node_modules/mapbox-map-image->export/node_modules/mosaic-image-stream/lib/stitch-image-stream.js:47:19)
>    at PixelMultiStream.EventEmitter.emit (/usr/local/lib/node_modules/mapbox-map-image->export/node_modules/events/events.js:81:17)
>    at PixelMultiStream.onFormat (/usr/local/lib/node_modules/mapbox-map-image->export/node_modules/mosaic-image-stream/lib/pixel-multi-stream.js:49:10)
>    at Pumpify.EventEmitter.emit (/usr/local/lib/node_modules/mapbox-map-image->export/node_modules/events/events.js:81:17)

A quick search indicates this might be at least somewhat [common](https://github.com/noseglid/atom-build/issues/481), but it's beyond my js skills to fix. Any idea if it's something that would be quick to remedy?

**Comment by gmaclennan** [comment]
Hi @kaluta this may be related to the node version you are running maybe? I'm not going to have any time to look at this for the next few weeks unfortunately.

**Comment by gmaclennan** [comment]
I just published `v2.2.0` which has some internal changes which might fix this problem. Let me know how it works.
