### ISSUE TITLE
Project is dead?

### ISSUE THREAD

**Issue by cardimajs** [digidem/mapbox-map-image-export#6]
I tried to use but it's not working.

not error messages and no image.

node v8.1.2

**Comment by gmaclennan** [comment]
We still use it, although I have not tried it with node v8. I would need more information to start understanding why it is not working for you.

**Comment by iaminawe** [comment]
what version of node do you use with it @gmaclennan ?

**Comment by gmaclennan** [comment]
I am using node v6.10.2. I just published v2.2.0 which might make things work better.

**Comment by iaminawe** [comment]
Thanks very much for the code update and info about the correct version of node.

I am loading the correct version of node now and have installed the updated code from your repo.

Unfortunately I cannot get even the sample posted on the repo to generate an image

export-map mapbox://styles/mapbox/streets-v9 -w=11in -h=8.5in \
  -b=-7.1354,57.9095,-6.1357,58.516 -t=$MAPBOX_TOKEN -o=lewis.png

It runs and just seems to get stuck - so far its been like that for an hour - does it run for a very long time? I am not getting any errors but it seems to be stuck as even outputting a very low res small sample didn't seem to work.

Any ideas for troubleshooting further?

I did notice these warnings during the install 

npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead

**Comment by gmaclennan** [comment]
I am unable to reproduce this unfortunately, it works for me.
Are you sure that `$MAPBOX_TOKEN` is defined? You should `export MAPBOX_TOKEN=your_mapbox_token` first. You can check it is defined with `echo $MAPBOX_TOKEN`. I am using node v6.10.2

are you on Windows or Mac or Linux? Which version of node are you using?

**Comment by iaminawe** [comment]
It totally works and is awesome - thank you so much. I was accidentally pasting in zoom, long, lat co-ordinates instead of the bounding box required. Going to have so much fun with this

**Comment by gmaclennan** [comment]
Could you share the command you entered? I should add a check on the arguments and throw an error.
