### ISSUE TITLE
Error {}, empty png created

### ISSUE THREAD

**Issue by ikmolbo** [digidem/mapbox-map-image-export#8]
Hi,

When I run the sample command, `export-map mapbox://styles/mapbox/streets-v9 -w=11in -h=8.5in -b=-7.1354,57.9095,-6.1357,58.516 -t=$MAPBOX_TOKEN -o=lewis.png`, I see `Error {}` in the console and the process doesn't seem to finish. The file lewis.png is created but contains zero bytes.

`echo  #$MAPBOX_TOKEN` shows that the correct API key is present.

Grateful for your help. I'm running node 6.10.2 and export-map version 2.2.1 on OSX.

Thanks!

**Comment by oblomki** [comment]
... now trying with node 6.10.2, and the error message is the same.
