### ISSUE TITLE
How to add pitch?

### ISSUE THREAD

**Issue by bbbford** [digidem/mapbox-map-image-export#9]
I'm attempting to add pitch, but it causes the process to hang.

I've tried adding pitch to mapMosaicStream and mapImageStream functions.

`map.jumpTo({
    center: viewport.center,
    zoom: viewport.zoom,
    pitch: 50
  })`

Any ideas?

**Comment by gmaclennan** [comment]
Hi @bbbford, this script works by splitting the requested area into tiles and exporting one at a time, then stitching those tiles together. The logic for tiling a map with a pitch is going to be quite complicated and hard to implement. I would be open to a PR on this if somebody got this working, but we’re not going to be working on it ourselves.
